version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ibanim
      POSTGRES_PASSWORD: ibanim
      POSTGRES_DB: ibanim
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: node:latest
    container_name: app
    working_dir: /usr/src/app
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: ibanim
      DB_PASS: ibanim
      DB_NAME: ibanim
    command: bash -c "npm install && npm start"
    ports:
      - "4880:4880"
    depends_on:
      - postgres

volumes:
  db: